
package com.starlix.service.id3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ID3global", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", wsdlLocation = "https://pilot.id3global.com/ID3gWS/ID3global.svc?wsdl")
public class ID3Global
    extends Service
{

    private final static URL ID3GLOBAL_WSDL_LOCATION;
    private final static WebServiceException ID3GLOBAL_EXCEPTION;
    private final static QName ID3GLOBAL_QNAME = new QName("http://www.id3global.com/ID3gWS/2013/04", "ID3global");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pilot.id3global.com/ID3gWS/ID3global.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ID3GLOBAL_WSDL_LOCATION = url;
        ID3GLOBAL_EXCEPTION = e;
    }

    public ID3Global() {
        super(__getWsdlLocation(), ID3GLOBAL_QNAME);
    }

    public ID3Global(WebServiceFeature... features) {
        super(__getWsdlLocation(), ID3GLOBAL_QNAME, features);
    }

    public ID3Global(URL wsdlLocation) {
        super(wsdlLocation, ID3GLOBAL_QNAME);
    }

    public ID3Global(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ID3GLOBAL_QNAME, features);
    }

    public ID3Global(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ID3Global(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCredentials")
    public IGlobalCredentials getBasicHttpBindingGlobalCredentials() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCredentials"), IGlobalCredentials.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCredentials")
    public IGlobalCredentials getBasicHttpBindingGlobalCredentials(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCredentials"), IGlobalCredentials.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCredentials")
    public IGlobalCredentials getWsHttpBindingGlobalCredentials() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCredentials"), IGlobalCredentials.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCredentials")
    public IGlobalCredentials getWsHttpBindingGlobalCredentials(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCredentials"), IGlobalCredentials.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalConfig")
    public IGlobalConfig getBasicHttpBindingGlobalConfig() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalConfig"), IGlobalConfig.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalConfig")
    public IGlobalConfig getBasicHttpBindingGlobalConfig(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalConfig"), IGlobalConfig.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalConfig")
    public IGlobalConfig getWsHttpBindingGlobalConfig() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalConfig"), IGlobalConfig.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalConfig")
    public IGlobalConfig getWsHttpBindingGlobalConfig(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalConfig"), IGlobalConfig.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalDocImage
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalDocImage")
    public IGlobalDocImage getBasicHttpBindingGlobalDocImage() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalDocImage"), IGlobalDocImage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalDocImage
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalDocImage")
    public IGlobalDocImage getBasicHttpBindingGlobalDocImage(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalDocImage"), IGlobalDocImage.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicHttpBindingGlobalProfile() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalProfile"), IGlobalProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalProfile"), IGlobalProfile.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicOAuthHttpBindingGlobalProfile() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalProfile"), IGlobalProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicOAuthHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalProfile"), IGlobalProfile.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalProfile")
    public IGlobalProfile getWsHttpBindingGlobalProfile() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalProfile"), IGlobalProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalProfile")
    public IGlobalProfile getWsHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalProfile"), IGlobalProfile.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getWsOAuthHttpBindingGlobalProfile() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalProfile"), IGlobalProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getWsOAuthHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalProfile"), IGlobalProfile.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicHttpBindingGlobalAuthenticate() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicOAuthHttpBindingGlobalAuthenticate() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicOAuthHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsHttpBindingGlobalAuthenticate() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsOAuthHttpBindingGlobalAuthenticate() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsOAuthHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalAuthenticate"), IGlobalAuthenticate.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalSearch
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSearch")
    public IGlobalSearch getBasicHttpBindingGlobalSearch() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSearch"), IGlobalSearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSearch
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSearch")
    public IGlobalSearch getBasicHttpBindingGlobalSearch(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSearch"), IGlobalSearch.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getBasicHttpBindingGlobalOrganisation() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalOrganisation"), IGlobalOrganisation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getBasicHttpBindingGlobalOrganisation(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalOrganisation"), IGlobalOrganisation.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getWsHttpBindingGlobalOrganisation() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalOrganisation"), IGlobalOrganisation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getWsHttpBindingGlobalOrganisation(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalOrganisation"), IGlobalOrganisation.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalMembership")
    public IGlobalMembership getBasicHttpBindingGlobalMembership() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalMembership"), IGlobalMembership.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalMembership")
    public IGlobalMembership getBasicHttpBindingGlobalMembership(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalMembership"), IGlobalMembership.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalMembership")
    public IGlobalMembership getWsHttpBindingGlobalMembership() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalMembership"), IGlobalMembership.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalMembership")
    public IGlobalMembership getWsHttpBindingGlobalMembership(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalMembership"), IGlobalMembership.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSupplier")
    public IGlobalSupplier getBasicHttpBindingGlobalSupplier() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSupplier"), IGlobalSupplier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSupplier")
    public IGlobalSupplier getBasicHttpBindingGlobalSupplier(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSupplier"), IGlobalSupplier.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalSupplier")
    public IGlobalSupplier getWsHttpBindingGlobalSupplier() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalSupplier"), IGlobalSupplier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalSupplier")
    public IGlobalSupplier getWsHttpBindingGlobalSupplier(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalSupplier"), IGlobalSupplier.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getBasicHttpBindingGlobalCaseManagement() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCaseManagement"), IGlobalCaseManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getBasicHttpBindingGlobalCaseManagement(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCaseManagement"), IGlobalCaseManagement.class, features);
    }

    /**
     * 
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getWsHttpBindingGlobalCaseManagement() {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCaseManagement"), IGlobalCaseManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getWsHttpBindingGlobalCaseManagement(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCaseManagement"), IGlobalCaseManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ID3GLOBAL_EXCEPTION!= null) {
            throw ID3GLOBAL_EXCEPTION;
        }
        return ID3GLOBAL_WSDL_LOCATION;
    }

}
