
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalOrganisation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalOrganisation {


    /**
     * 
     * @param adminName
     * @param adminUsername
     * @param parentOrgID
     * @param organisationDetails
     * @param adminPIN
     * @param adminEmail
     * @param adminPassword
     * @return
     *     returns com.starlix.service.id3.GlobalOrganisation
     * @throws IGlobalOrganisationCreateOrganisationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateOrganisation", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalOrganisation/CreateOrganisation")
    @WebResult(name = "CreateOrganisationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CreateOrganisation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateOrganisation")
    @ResponseWrapper(localName = "CreateOrganisationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateOrganisationResponse")
    public GlobalOrganisation createOrganisation(
        @WebParam(name = "ParentOrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String parentOrgID,
        @WebParam(name = "OrganisationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalOrganisationDetails organisationDetails,
        @WebParam(name = "AdminName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String adminName,
        @WebParam(name = "AdminUsername", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String adminUsername,
        @WebParam(name = "AdminEmail", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String adminEmail,
        @WebParam(name = "AdminPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String adminPassword,
        @WebParam(name = "AdminPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String adminPIN)
        throws IGlobalOrganisationCreateOrganisationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param organisationDetails
     * @throws IGlobalOrganisationUpdateOrganisationDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateOrganisationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalOrganisation/UpdateOrganisationDetails")
    @RequestWrapper(localName = "UpdateOrganisationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateOrganisationDetails")
    @ResponseWrapper(localName = "UpdateOrganisationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateOrganisationDetailsResponse")
    public void updateOrganisationDetails(
        @WebParam(name = "OrganisationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalOrganisationDetails organisationDetails)
        throws IGlobalOrganisationUpdateOrganisationDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param parentOrgID
     * @param pageSize
     * @param page
     * @return
     *     returns com.starlix.service.id3.GlobalOrganisations
     * @throws IGlobalOrganisationGetOrganisationsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetOrganisations", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalOrganisation/GetOrganisations")
    @WebResult(name = "GetOrganisationsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetOrganisations", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrganisations")
    @ResponseWrapper(localName = "GetOrganisationsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrganisationsResponse")
    public GlobalOrganisations getOrganisations(
        @WebParam(name = "ParentOrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String parentOrgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalOrganisationGetOrganisationsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalOrganisationDetails
     * @throws IGlobalOrganisationGetOrganisationDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetOrganisationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalOrganisation/GetOrganisationDetails")
    @WebResult(name = "GetOrganisationDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetOrganisationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrganisationDetails")
    @ResponseWrapper(localName = "GetOrganisationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrganisationDetailsResponse")
    public GlobalOrganisationDetails getOrganisationDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID)
        throws IGlobalOrganisationGetOrganisationDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalHome
     * @throws IGlobalOrganisationGetHomeID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetHome", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalOrganisation/GetHome")
    @WebResult(name = "GetHomeResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetHome", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetHome")
    @ResponseWrapper(localName = "GetHomeResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetHomeResponse")
    public GlobalHome getHome(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID)
        throws IGlobalOrganisationGetHomeID3GExceptionFaultFaultMessage
    ;

}
