
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalCredentials", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalCredentials {


    /**
     * 
     * @param password
     * @param accountName
     * @return
     *     returns com.starlix.service.id3.GlobalAccount
     * @throws IGlobalCredentialsCheckCredentialsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckCredentials", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentials")
    @WebResult(name = "CheckCredentialsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CheckCredentials", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckCredentials")
    @ResponseWrapper(localName = "CheckCredentialsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckCredentialsResponse")
    public GlobalAccount checkCredentials(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password)
        throws IGlobalCredentialsCheckCredentialsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param nonce
     * @return
     *     returns com.starlix.service.id3.GlobalAccount
     * @throws IGlobalCredentialsCheckNonceID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckNonce", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckNonce")
    @WebResult(name = "CheckNonceResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CheckNonce", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckNonce")
    @ResponseWrapper(localName = "CheckNonceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckNonceResponse")
    public GlobalAccount checkNonce(
        @WebParam(name = "Nonce", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String nonce)
        throws IGlobalCredentialsCheckNonceID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param accountName
     * @return
     *     returns java.lang.String
     * @throws IGlobalCredentialsGetPINSequenceID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPINSequence", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPINSequence")
    @WebResult(name = "GetPINSequenceResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPINSequence")
    @ResponseWrapper(localName = "GetPINSequenceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPINSequenceResponse")
    public String getPINSequence(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password)
        throws IGlobalCredentialsGetPINSequenceID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param accountName
     * @param pinSequence
     * @return
     *     returns com.starlix.service.id3.GlobalAccount
     * @throws IGlobalCredentialsCheckCredentialsWithPINID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckCredentialsWithPIN", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsWithPIN")
    @WebResult(name = "CheckCredentialsWithPINResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CheckCredentialsWithPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckCredentialsWithPIN")
    @ResponseWrapper(localName = "CheckCredentialsWithPINResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckCredentialsWithPINResponse")
    public GlobalAccount checkCredentialsWithPIN(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pinSequence)
        throws IGlobalCredentialsCheckCredentialsWithPINID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param accountName
     * @param pinSequence
     * @param newPassword
     * @throws IGlobalCredentialsChangePasswordID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ChangePassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePassword")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pinSequence,
        @WebParam(name = "NewPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String newPassword)
        throws IGlobalCredentialsChangePasswordID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param accountName
     * @param pinSequence
     * @param newPIN
     * @throws IGlobalCredentialsChangePINID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ChangePIN", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePIN")
    @RequestWrapper(localName = "ChangePIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePIN")
    @ResponseWrapper(localName = "ChangePINResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePINResponse")
    public void changePIN(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pinSequence,
        @WebParam(name = "NewPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String newPIN)
        throws IGlobalCredentialsChangePINID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param reminder
     * @param accountName
     * @param pinSequence
     * @param newPIN
     * @throws IGlobalCredentialsChangePINWithReminderID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ChangePINWithReminder", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINWithReminder")
    @RequestWrapper(localName = "ChangePINWithReminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePINWithReminder")
    @ResponseWrapper(localName = "ChangePINWithReminderResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ChangePINWithReminderResponse")
    public void changePINWithReminder(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pinSequence,
        @WebParam(name = "NewPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String newPIN,
        @WebParam(name = "Reminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String reminder)
        throws IGlobalCredentialsChangePINWithReminderID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param email
     * @throws IGlobalCredentialsForgotAccountID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ForgotAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccount")
    @RequestWrapper(localName = "ForgotAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotAccount")
    @ResponseWrapper(localName = "ForgotAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotAccountResponse")
    public void forgotAccount(
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String email)
        throws IGlobalCredentialsForgotAccountID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param email
     * @param productName
     * @throws IGlobalCredentialsForgotAccountForProductID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ForgotAccountForProduct", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountForProduct")
    @RequestWrapper(localName = "ForgotAccountForProduct", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotAccountForProduct")
    @ResponseWrapper(localName = "ForgotAccountForProductResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotAccountForProductResponse")
    public void forgotAccountForProduct(
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String email,
        @WebParam(name = "ProductName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String productName)
        throws IGlobalCredentialsForgotAccountForProductID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountName
     * @throws IGlobalCredentialsForgotPasswordID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ForgotPassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotPassword")
    @RequestWrapper(localName = "ForgotPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotPassword")
    @ResponseWrapper(localName = "ForgotPasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForgotPasswordResponse")
    public void forgotPassword(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName)
        throws IGlobalCredentialsForgotPasswordID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountName
     * @throws IGlobalCredentialsRequestMemorableWordReminderID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RequestMemorableWordReminder", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/RequestMemorableWordReminder")
    @RequestWrapper(localName = "RequestMemorableWordReminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RequestMemorableWordReminder")
    @ResponseWrapper(localName = "RequestMemorableWordReminderResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RequestMemorableWordReminderResponse")
    public void requestMemorableWordReminder(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName)
        throws IGlobalCredentialsRequestMemorableWordReminderID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountName
     * @return
     *     returns com.starlix.service.id3.GlobalPasswordPolicy
     * @throws IGlobalCredentialsGetPasswordPolicyForUserID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPasswordPolicyForUser", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPasswordPolicyForUser")
    @WebResult(name = "GetPasswordPolicyForUserResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPasswordPolicyForUser", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPasswordPolicyForUser")
    @ResponseWrapper(localName = "GetPasswordPolicyForUserResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPasswordPolicyForUserResponse")
    public GlobalPasswordPolicy getPasswordPolicyForUser(
        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountName)
        throws IGlobalCredentialsGetPasswordPolicyForUserID3GExceptionFaultFaultMessage
    ;

}
