
package com.starlix.service.id3;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalCaseManagement", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalCaseManagement {


    /**
     * 
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCaseProfileVersion
     * @throws IGlobalCaseManagementGetGlobalCaseProfileVersionsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetGlobalCaseProfileVersions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetGlobalCaseProfileVersions")
    @WebResult(name = "GetGlobalCaseProfileVersionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetGlobalCaseProfileVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetGlobalCaseProfileVersions")
    @ResponseWrapper(localName = "GetGlobalCaseProfileVersionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetGlobalCaseProfileVersionsResponse")
    public ArrayOfGlobalCaseProfileVersion getGlobalCaseProfileVersions(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID)
        throws IGlobalCaseManagementGetGlobalCaseProfileVersionsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseNotifications
     * @throws IGlobalCaseManagementGetCaseNotificationsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCaseNotifications", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotifications")
    @WebResult(name = "GetCaseNotificationsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCaseNotifications", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseNotifications")
    @ResponseWrapper(localName = "GetCaseNotificationsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseNotificationsResponse")
    public GlobalCaseNotifications getCaseNotifications(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize)
        throws IGlobalCaseManagementGetCaseNotificationsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseNotification
     * @throws IGlobalCaseManagementGetCaseNotificationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCaseNotification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotification")
    @WebResult(name = "GetCaseNotificationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCaseNotification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseNotification")
    @ResponseWrapper(localName = "GetCaseNotificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseNotificationResponse")
    public GlobalCaseNotification getCaseNotification(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID)
        throws IGlobalCaseManagementGetCaseNotificationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param jobs
     * @param orgID
     * @throws IGlobalCaseManagementUpdateCaseNotificationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateCaseNotification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseNotification")
    @RequestWrapper(localName = "UpdateCaseNotification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCaseNotification")
    @ResponseWrapper(localName = "UpdateCaseNotificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCaseNotificationResponse")
    public void updateCaseNotification(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Jobs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseNotificationJob jobs)
        throws IGlobalCaseManagementUpdateCaseNotificationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseCustomerSettings
     * @throws IGlobalCaseManagementGetCustomerSettingsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomerSettings", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCustomerSettings")
    @WebResult(name = "GetCustomerSettingsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCustomerSettings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCustomerSettings")
    @ResponseWrapper(localName = "GetCustomerSettingsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCustomerSettingsResponse")
    public GlobalCaseCustomerSettings getCustomerSettings(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID)
        throws IGlobalCaseManagementGetCustomerSettingsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param settings
     * @param orgID
     * @throws IGlobalCaseManagementUpdateCustomerSettingsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateCustomerSettings", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCustomerSettings")
    @RequestWrapper(localName = "UpdateCustomerSettings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCustomerSettings")
    @ResponseWrapper(localName = "UpdateCustomerSettingsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCustomerSettingsResponse")
    public void updateCustomerSettings(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Settings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseCustomerSettings settings)
        throws IGlobalCaseManagementUpdateCustomerSettingsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param profileID
     * @param caseID
     * @param authenticationID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementRaiseChargingPointID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RaiseChargingPoint", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RaiseChargingPoint")
    @WebResult(name = "RaiseChargingPointResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "RaiseChargingPoint", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RaiseChargingPoint")
    @ResponseWrapper(localName = "RaiseChargingPointResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RaiseChargingPointResponse")
    public GlobalCaseDetails raiseChargingPoint(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "ProfileID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String profileID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID)
        throws IGlobalCaseManagementRaiseChargingPointID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param documents
     * @param caseID
     * @param orgID
     * @throws IGlobalCaseManagementSaveCaseDocumentsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SaveCaseDocuments", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveCaseDocuments")
    @RequestWrapper(localName = "SaveCaseDocuments", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveCaseDocuments")
    @ResponseWrapper(localName = "SaveCaseDocumentsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveCaseDocumentsResponse")
    public void saveCaseDocuments(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseDocument documents)
        throws IGlobalCaseManagementSaveCaseDocumentsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param param
     * @param caseID
     * @param results
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementSaveDocumentResultID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SaveDocumentResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveDocumentResult")
    @WebResult(name = "SaveDocumentResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "SaveDocumentResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveDocumentResult")
    @ResponseWrapper(localName = "SaveDocumentResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveDocumentResultResponse")
    public GlobalCaseDetails saveDocumentResult(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Results", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseDocumentResult results,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseDocumentResultParameters param)
        throws IGlobalCaseManagementSaveDocumentResultID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param param
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementSaveExternalDataResultID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SaveExternalDataResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveExternalDataResult")
    @WebResult(name = "SaveExternalDataResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "SaveExternalDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveExternalDataResult")
    @ResponseWrapper(localName = "SaveExternalDataResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveExternalDataResultResponse")
    public GlobalCaseDetails saveExternalDataResult(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalExternalDataResultParameters param)
        throws IGlobalCaseManagementSaveExternalDataResultID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param param
     * @param caseID
     * @param results
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementSaveResultID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SaveResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveResult")
    @WebResult(name = "SaveResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "SaveResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveResult")
    @ResponseWrapper(localName = "SaveResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveResultResponse")
    public GlobalCaseDetails saveResult(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Results", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalResultData results,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseResultParameters param)
        throws IGlobalCaseManagementSaveResultID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param state
     * @param orgID
     * @param actionContext
     * @throws IGlobalCaseManagementUpdateStateID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateState", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateState")
    @RequestWrapper(localName = "UpdateState", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateState")
    @ResponseWrapper(localName = "UpdateStateResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateStateResponse")
    public void updateState(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long state,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long actionContext)
        throws IGlobalCaseManagementUpdateStateID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param result
     * @param param
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementSaveManualDispatchResultID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SaveManualDispatchResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveManualDispatchResult")
    @WebResult(name = "SaveManualDispatchResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "SaveManualDispatchResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveManualDispatchResult")
    @ResponseWrapper(localName = "SaveManualDispatchResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SaveManualDispatchResultResponse")
    public GlobalCaseDetails saveManualDispatchResult(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseDispatchParameters param,
        @WebParam(name = "Result", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalDispatchResult result)
        throws IGlobalCaseManagementSaveManualDispatchResultID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param params
     * @param orgID
     * @throws IGlobalCaseManagementDispatchCaseID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DispatchCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/DispatchCase")
    @RequestWrapper(localName = "DispatchCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DispatchCase")
    @ResponseWrapper(localName = "DispatchCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DispatchCaseResponse")
    public void dispatchCase(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Params", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseDispatchParameters params)
        throws IGlobalCaseManagementDispatchCaseID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param service
     * @param source
     * @throws IGlobalCaseManagementRetrieveDispatchID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "RetrieveDispatch", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RetrieveDispatch")
    @RequestWrapper(localName = "RetrieveDispatch", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RetrieveDispatch")
    @ResponseWrapper(localName = "RetrieveDispatchResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.RetrieveDispatchResponse")
    public void retrieveDispatch(
        @WebParam(name = "Source", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String source,
        @WebParam(name = "Service", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseDispatchServiceType service)
        throws IGlobalCaseManagementRetrieveDispatchID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param reference
     * @param inputData
     * @param linkedAccountId
     * @param productId
     * @param authorType
     * @param customerReferences
     * @param name
     * @param profiles
     * @param state
     * @param orgID
     * @param properties
     * @param actionContext
     * @return
     *     returns java.lang.String
     * @throws IGlobalCaseManagementCreateCaseID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateCase")
    @WebResult(name = "CreateCaseResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CreateCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateCase")
    @ResponseWrapper(localName = "CreateCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateCaseResponse")
    public String createCase(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "LinkedAccountId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String linkedAccountId,
        @WebParam(name = "Reference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String reference,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer authorType,
        @WebParam(name = "ProductId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String productId,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseReference customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalKeyValuePairOfstringstring properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalProfileIDVersion profiles,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalCaseManagementCreateCaseID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param inputData
     * @param linkedAccountId
     * @param productId
     * @param documents
     * @param authorType
     * @param customerReferences
     * @param profiles
     * @param documentCategorySubmissionTypes
     * @param orgID
     * @param actionContext
     * @param reference
     * @param verdict
     * @param name
     * @param consents
     * @param disclaimerAccepted
     * @param state
     * @param properties
     * @return
     *     returns java.lang.String
     * @throws IGlobalCaseManagementCreateFullCaseID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateFullCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateFullCase")
    @WebResult(name = "CreateFullCaseResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CreateFullCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateFullCase")
    @ResponseWrapper(localName = "CreateFullCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateFullCaseResponse")
    public String createFullCase(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "LinkedAccountId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String linkedAccountId,
        @WebParam(name = "Reference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String reference,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer authorType,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer verdict,
        @WebParam(name = "ProductId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String productId,
        @WebParam(name = "DisclaimerAccepted", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean disclaimerAccepted,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseReference customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalKeyValuePairOfstringstring properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalProfileIDVersion profiles,
        @WebParam(name = "DocumentCategorySubmissionTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalDocumentCategorySubmissionType documentCategorySubmissionTypes,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseDocument documents,
        @WebParam(name = "Consents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseConsent consents,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalCaseManagementCreateFullCaseID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param inputData
     * @param documents
     * @param authorType
     * @param customerReferences
     * @param profiles
     * @param documentCategorySubmissionTypes
     * @param orgID
     * @param actionContext
     * @param caseID
     * @param verdict
     * @param name
     * @param consents
     * @param disclaimerAccepted
     * @param state
     * @param properties
     * @throws IGlobalCaseManagementUpdateCaseID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCase")
    @RequestWrapper(localName = "UpdateCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCase")
    @ResponseWrapper(localName = "UpdateCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCaseResponse")
    public void updateCase(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer authorType,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer verdict,
        @WebParam(name = "DisclaimerAccepted", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean disclaimerAccepted,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseReference customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalKeyValuePairOfstringstring properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalProfileIDVersion profiles,
        @WebParam(name = "DocumentCategorySubmissionTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalDocumentCategorySubmissionType documentCategorySubmissionTypes,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseDocument documents,
        @WebParam(name = "Consents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalCaseConsent consents,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalCaseManagementUpdateCaseID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param orgID
     * @param email
     * @throws IGlobalCaseManagementUpdateCaseEmailID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateCaseEmail", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseEmail")
    @RequestWrapper(localName = "UpdateCaseEmail", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCaseEmail")
    @ResponseWrapper(localName = "UpdateCaseEmailResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateCaseEmailResponse")
    public void updateCaseEmail(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String email)
        throws IGlobalCaseManagementUpdateCaseEmailID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fromDate
     * @param includeDocuments
     * @param verdict
     * @param toDate
     * @param name
     * @param pageSize
     * @param page
     * @param state
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCases
     * @throws IGlobalCaseManagementGetCasesID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCases", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCases")
    @WebResult(name = "GetCasesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCases", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCases")
    @ResponseWrapper(localName = "GetCasesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCasesResponse")
    public GlobalCases getCases(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long state,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long verdict,
        @WebParam(name = "FromDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar toDate,
        @WebParam(name = "IncludeDocuments", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean includeDocuments)
        throws IGlobalCaseManagementGetCasesID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalCaseDetails
     * @throws IGlobalCaseManagementGetCaseDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCaseDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseDetails")
    @WebResult(name = "GetCaseDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCaseDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseDetails")
    @ResponseWrapper(localName = "GetCaseDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseDetailsResponse")
    public GlobalCaseDetails getCaseDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID)
        throws IGlobalCaseManagementGetCaseDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalInputData
     * @throws IGlobalCaseManagementGetCaseInputDataID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCaseInputData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseInputData")
    @WebResult(name = "GetCaseInputDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCaseInputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseInputData")
    @ResponseWrapper(localName = "GetCaseInputDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseInputDataResponse")
    public GlobalInputData getCaseInputData(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID)
        throws IGlobalCaseManagementGetCaseInputDataID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param caseID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCaseState
     * @throws IGlobalCaseManagementGetCaseAuditRecordID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetCaseAuditRecord", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseAuditRecord")
    @WebResult(name = "GetCaseAuditRecordResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCaseAuditRecord", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseAuditRecord")
    @ResponseWrapper(localName = "GetCaseAuditRecordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCaseAuditRecordResponse")
    public ArrayOfGlobalCaseState getCaseAuditRecord(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID)
        throws IGlobalCaseManagementGetCaseAuditRecordID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param param
     * @param caseID
     * @param orgID
     * @throws IGlobalCaseManagementUpdateDispatchStatusID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateDispatchStatus", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateDispatchStatus")
    @RequestWrapper(localName = "UpdateDispatchStatus", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateDispatchStatus")
    @ResponseWrapper(localName = "UpdateDispatchStatusResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateDispatchStatusResponse")
    public void updateDispatchStatus(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCaseDispatchParameters param)
        throws IGlobalCaseManagementUpdateDispatchStatusID3GExceptionFaultFaultMessage
    ;

}
