
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalAuthenticate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalAuthenticate {


    /**
     * 
     * @param inputData
     * @param customerReference
     * @param profileIDVersion
     * @return
     *     returns com.starlix.service.id3.GlobalResultData
     * @throws IGlobalAuthenticateAuthenticateSPID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AuthenticateSP", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateSP")
    @WebResult(name = "AuthenticateSPResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "AuthenticateSP", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AuthenticateSP")
    @ResponseWrapper(localName = "AuthenticateSPResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AuthenticateSPResponse")
    public GlobalResultData authenticateSP(
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalProfileIDVersion profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalAuthenticateAuthenticateSPID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param inputData
     * @param customerReference
     * @param authenticationID
     * @param profileIDVersion
     * @return
     *     returns com.starlix.service.id3.GlobalResultData
     * @throws IGlobalAuthenticateIncrementalVerificationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "IncrementalVerification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/IncrementalVerification")
    @WebResult(name = "IncrementalVerificationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "IncrementalVerification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.IncrementalVerification")
    @ResponseWrapper(localName = "IncrementalVerificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.IncrementalVerificationResponse")
    public GlobalResultData incrementalVerification(
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalProfileIDVersion profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalAuthenticateIncrementalVerificationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param inputData
     * @param profileIDVersions
     * @param customerReference
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalResultData
     * @throws IGlobalAuthenticateAuthenticateMPID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AuthenticateMP", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateMP")
    @WebResult(name = "AuthenticateMPResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "AuthenticateMP", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AuthenticateMP")
    @ResponseWrapper(localName = "AuthenticateMPResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AuthenticateMPResponse")
    public ArrayOfGlobalResultData authenticateMP(
        @WebParam(name = "ProfileIDVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalProfileIDVersion profileIDVersions,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData)
        throws IGlobalAuthenticateAuthenticateMPID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param customerReference
     * @param authenticationID
     * @param overrides
     * @param profileIDVersion
     * @return
     *     returns com.starlix.service.id3.GlobalResultData
     * @throws IGlobalAuthenticateForceOverrideID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ForceOverride", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/ForceOverride")
    @WebResult(name = "ForceOverrideResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "ForceOverride", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForceOverride")
    @ResponseWrapper(localName = "ForceOverrideResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ForceOverrideResponse")
    public GlobalResultData forceOverride(
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalProfileIDVersion profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String customerReference,
        @WebParam(name = "Overrides", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalOverride overrides)
        throws IGlobalAuthenticateForceOverrideID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param inputData
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalAddress
     * @throws IGlobalAuthenticateAddressLookupID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AddressLookup", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AddressLookup")
    @WebResult(name = "AddressLookupResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "AddressLookup", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AddressLookup")
    @ResponseWrapper(localName = "AddressLookupResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AddressLookupResponse")
    public ArrayOfGlobalAddress addressLookup(
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalAddress inputData)
        throws IGlobalAuthenticateAddressLookupID3GExceptionFaultFaultMessage
    ;

}
