
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalSupplier", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalSupplier {


    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSupplier
     * @throws IGlobalSupplierGetSuppliersID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSuppliers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSuppliers")
    @WebResult(name = "GetSuppliersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSuppliers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSuppliers")
    @ResponseWrapper(localName = "GetSuppliersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSuppliersResponse")
    public ArrayOfGlobalSupplier getSuppliers()
        throws IGlobalSupplierGetSuppliersID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSupplierFlags
     * @throws IGlobalSupplierGetSupplierFlagsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierFlags", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierFlags")
    @WebResult(name = "GetSupplierFlagsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierFlags", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierFlags")
    @ResponseWrapper(localName = "GetSupplierFlagsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierFlagsResponse")
    public ArrayOfGlobalSupplierFlags getSupplierFlags()
        throws IGlobalSupplierGetSupplierFlagsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param supplier
     * @throws IGlobalSupplierUpdateSupplierID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateSupplier", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplier")
    @RequestWrapper(localName = "UpdateSupplier", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateSupplier")
    @ResponseWrapper(localName = "UpdateSupplierResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateSupplierResponse")
    public void updateSupplier(
        @WebParam(name = "Supplier", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalSupplier supplier)
        throws IGlobalSupplierUpdateSupplierID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param supplierID
     * @param pageSize
     * @param page
     * @return
     *     returns com.starlix.service.id3.GlobalSupplierAccounts
     * @throws IGlobalSupplierGetSupplierAccountsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierAccounts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccounts")
    @WebResult(name = "GetSupplierAccountsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierAccounts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierAccounts")
    @ResponseWrapper(localName = "GetSupplierAccountsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierAccountsResponse")
    public GlobalSupplierAccounts getSupplierAccounts(
        @WebParam(name = "SupplierID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String supplierID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalSupplierGetSupplierAccountsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param supplierAccountID
     * @return
     *     returns com.starlix.service.id3.GlobalSupplierAccount
     * @throws IGlobalSupplierGetSupplierAccountID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccount")
    @WebResult(name = "GetSupplierAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierAccount")
    @ResponseWrapper(localName = "GetSupplierAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierAccountResponse")
    public GlobalSupplierAccount getSupplierAccount(
        @WebParam(name = "SupplierAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String supplierAccountID)
        throws IGlobalSupplierGetSupplierAccountID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param supplierAccount
     * @return
     *     returns com.starlix.service.id3.GlobalSupplierAccount
     * @throws IGlobalSupplierTestSupplierAccountCredentialsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "TestSupplierAccountCredentials", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/TestSupplierAccountCredentials")
    @WebResult(name = "TestSupplierAccountCredentialsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "TestSupplierAccountCredentials", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.TestSupplierAccountCredentials")
    @ResponseWrapper(localName = "TestSupplierAccountCredentialsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.TestSupplierAccountCredentialsResponse")
    public GlobalSupplierAccount testSupplierAccountCredentials(
        @WebParam(name = "SupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalSupplierAccount supplierAccount)
        throws IGlobalSupplierTestSupplierAccountCredentialsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param supplierAccount
     * @return
     *     returns com.starlix.service.id3.GlobalSupplierAccount
     * @throws IGlobalSupplierUpdateSupplierAccountID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateSupplierAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierAccount")
    @WebResult(name = "UpdateSupplierAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "UpdateSupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateSupplierAccount")
    @ResponseWrapper(localName = "UpdateSupplierAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateSupplierAccountResponse")
    public GlobalSupplierAccount updateSupplierAccount(
        @WebParam(name = "SupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalSupplierAccount supplierAccount)
        throws IGlobalSupplierUpdateSupplierAccountID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param supplierid
     * @return
     *     returns com.starlix.service.id3.GlobalSupplierConfig
     * @throws IGlobalSupplierGetSupplierFieldsBySupplierIdID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierFieldsBySupplierId", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierFieldsBySupplierId")
    @WebResult(name = "GetSupplierFieldsBySupplierIdResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierFieldsBySupplierId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierFieldsBySupplierId")
    @ResponseWrapper(localName = "GetSupplierFieldsBySupplierIdResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierFieldsBySupplierIdResponse")
    public GlobalSupplierConfig getSupplierFieldsBySupplierId(
        @WebParam(name = "supplierid", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String supplierid)
        throws IGlobalSupplierGetSupplierFieldsBySupplierIdID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSupplierConfig
     * @throws IGlobalSupplierGetSupplierConfigID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierConfig", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierConfig")
    @WebResult(name = "GetSupplierConfigResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierConfig", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierConfig")
    @ResponseWrapper(localName = "GetSupplierConfigResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierConfigResponse")
    public ArrayOfGlobalSupplierConfig getSupplierConfig()
        throws IGlobalSupplierGetSupplierConfigID3GExceptionFaultFaultMessage
    ;

}
