
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalMembership", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalMembership {


    /**
     * 
     * @param password
     * @param passwordNeverExpires
     * @param roleIDs
     * @param pin
     * @param name
     * @param orgID
     * @param email
     * @param username
     * @return
     *     returns com.starlix.service.id3.GlobalAccount
     * @throws IGlobalMembershipCreateAccountID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateAccount")
    @WebResult(name = "CreateAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CreateAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateAccount")
    @ResponseWrapper(localName = "CreateAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateAccountResponse")
    public GlobalAccount createAccount(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "Username", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String username,
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String email,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password,
        @WebParam(name = "PIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pin,
        @WebParam(name = "PasswordNeverExpires", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean passwordNeverExpires,
        @WebParam(name = "RoleIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfguid roleIDs)
        throws IGlobalMembershipCreateAccountID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalAccounts
     * @throws IGlobalMembershipGetAccountsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccounts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccounts")
    @WebResult(name = "GetAccountsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAccounts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccounts")
    @ResponseWrapper(localName = "GetAccountsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountsResponse")
    public GlobalAccounts getAccounts(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalMembershipGetAccountsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalAccountDetails
     * @throws IGlobalMembershipGetAccountDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountDetails")
    @WebResult(name = "GetAccountDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAccountDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountDetails")
    @ResponseWrapper(localName = "GetAccountDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountDetailsResponse")
    public GlobalAccountDetails getAccountDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountID)
        throws IGlobalMembershipGetAccountDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param product
     * @param orgID
     * @return
     *     returns java.lang.String
     * @throws IGlobalMembershipGetOrgAdminAccountIDID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetOrgAdminAccountID", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetOrgAdminAccountID")
    @WebResult(name = "GetOrgAdminAccountIDResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetOrgAdminAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrgAdminAccountID")
    @ResponseWrapper(localName = "GetOrgAdminAccountIDResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetOrgAdminAccountIDResponse")
    public String getOrgAdminAccountID(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Product", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalProduct product)
        throws IGlobalMembershipGetOrgAdminAccountIDID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param account
     * @throws IGlobalMembershipUpdateAccountDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateAccountDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateAccountDetails")
    @RequestWrapper(localName = "UpdateAccountDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAccountDetails")
    @ResponseWrapper(localName = "UpdateAccountDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAccountDetailsResponse")
    public void updateAccountDetails(
        @WebParam(name = "Account", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalAccountDetails account)
        throws IGlobalMembershipUpdateAccountDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountID
     * @param password
     * @param orgID
     * @throws IGlobalMembershipResetPasswordID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ResetPassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/ResetPassword")
    @RequestWrapper(localName = "ResetPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ResetPassword")
    @ResponseWrapper(localName = "ResetPasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.ResetPasswordResponse")
    public void resetPassword(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountID,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password)
        throws IGlobalMembershipResetPasswordID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param accountID
     * @param search
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalRoles
     * @throws IGlobalMembershipGetAccountRolesID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountRoles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountRoles")
    @WebResult(name = "GetAccountRolesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAccountRoles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountRoles")
    @ResponseWrapper(localName = "GetAccountRolesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountRolesResponse")
    public GlobalRoles getAccountRoles(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String accountID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalMembershipGetAccountRolesID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param resourceID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalPermission
     * @throws IGlobalMembershipGetAccountPermissionID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountPermission", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountPermission")
    @WebResult(name = "GetAccountPermissionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAccountPermission", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountPermission")
    @ResponseWrapper(localName = "GetAccountPermissionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountPermissionResponse")
    public GlobalPermission getAccountPermission(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String resourceID)
        throws IGlobalMembershipGetAccountPermissionID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param name
     * @param description
     * @param isAdminPolicy
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalRole
     * @throws IGlobalMembershipCreateRoleID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateRole", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateRole")
    @WebResult(name = "CreateRoleResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CreateRole", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateRole")
    @ResponseWrapper(localName = "CreateRoleResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateRoleResponse")
    public GlobalRole createRole(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "Description", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String description,
        @WebParam(name = "IsAdminPolicy", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean isAdminPolicy)
        throws IGlobalMembershipCreateRoleID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalRoles
     * @throws IGlobalMembershipGetRolesID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetRoles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoles")
    @WebResult(name = "GetRolesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRoles")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRolesResponse")
    public GlobalRoles getRoles(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalMembershipGetRolesID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param role
     * @param orgID
     * @throws IGlobalMembershipUpdateRoleID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateRole", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRole")
    @RequestWrapper(localName = "UpdateRole", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateRole")
    @ResponseWrapper(localName = "UpdateRoleResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateRoleResponse")
    public void updateRole(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Role", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalRole role)
        throws IGlobalMembershipUpdateRoleID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param roleID
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalRoleMembers
     * @throws IGlobalMembershipGetRoleMembersID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetRoleMembers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoleMembers")
    @WebResult(name = "GetRoleMembersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetRoleMembers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRoleMembers")
    @ResponseWrapper(localName = "GetRoleMembersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRoleMembersResponse")
    public GlobalRoleMembers getRoleMembers(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String roleID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalMembershipGetRoleMembersID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param roleID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalResource
     * @throws IGlobalMembershipGetRolePermissionsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetRolePermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolePermissions")
    @WebResult(name = "GetRolePermissionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRolePermissions")
    @ResponseWrapper(localName = "GetRolePermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetRolePermissionsResponse")
    public ArrayOfGlobalResource getRolePermissions(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String roleID)
        throws IGlobalMembershipGetRolePermissionsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param addAccountIDs
     * @param roleID
     * @param orgID
     * @param removeAccountIDs
     * @throws IGlobalMembershipUpdateRoleMembersID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateRoleMembers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleMembers")
    @RequestWrapper(localName = "UpdateRoleMembers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateRoleMembers")
    @ResponseWrapper(localName = "UpdateRoleMembersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateRoleMembersResponse")
    public void updateRoleMembers(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String roleID,
        @WebParam(name = "AddAccountIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfguid addAccountIDs,
        @WebParam(name = "RemoveAccountIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfguid removeAccountIDs)
        throws IGlobalMembershipUpdateRoleMembersID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param resourceID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalRolePermission
     * @throws IGlobalMembershipGetPermissionsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetPermissions")
    @WebResult(name = "GetPermissionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPermissions")
    @ResponseWrapper(localName = "GetPermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPermissionsResponse")
    public ArrayOfGlobalRolePermission getPermissions(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String resourceID)
        throws IGlobalMembershipGetPermissionsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param resourceID
     * @param removeRolePermissions
     * @param addRolePermissions
     * @param orgID
     * @throws IGlobalMembershipUpdatePermissionsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdatePermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdatePermissions")
    @RequestWrapper(localName = "UpdatePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdatePermissions")
    @ResponseWrapper(localName = "UpdatePermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdatePermissionsResponse")
    public void updatePermissions(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String resourceID,
        @WebParam(name = "AddRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalRolePermission addRolePermissions,
        @WebParam(name = "RemoveRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalRolePermission removeRolePermissions)
        throws IGlobalMembershipUpdatePermissionsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param orgID
     * @throws IGlobalMembershipSendWelcomeEmailID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "SendWelcomeEmail", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/SendWelcomeEmail")
    @RequestWrapper(localName = "SendWelcomeEmail", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SendWelcomeEmail")
    @ResponseWrapper(localName = "SendWelcomeEmailResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SendWelcomeEmailResponse")
    public void sendWelcomeEmail(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID)
        throws IGlobalMembershipSendWelcomeEmailID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param password
     * @param roleIDs
     * @param orgID
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws IGlobalMembershipCheckNewAccountAgainstPasswordPoliciesID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CheckNewAccountAgainstPasswordPolicies", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CheckNewAccountAgainstPasswordPolicies")
    @WebResult(name = "CheckNewAccountAgainstPasswordPoliciesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "CheckNewAccountAgainstPasswordPolicies", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckNewAccountAgainstPasswordPolicies")
    @ResponseWrapper(localName = "CheckNewAccountAgainstPasswordPoliciesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CheckNewAccountAgainstPasswordPoliciesResponse")
    public Boolean checkNewAccountAgainstPasswordPolicies(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "RoleIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfguid roleIDs,
        @WebParam(name = "Username", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String password)
        throws IGlobalMembershipCheckNewAccountAgainstPasswordPoliciesID3GExceptionFaultFaultMessage
    ;

}
