
package com.starlix.service.id3;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalConfig", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalConfig {


    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetDocImageMinSizeKBytes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinSizeKBytes")
    @WebResult(name = "GetDocImageMinSizeKBytesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocImageMinSizeKBytes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinSizeKBytes")
    @ResponseWrapper(localName = "GetDocImageMinSizeKBytesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinSizeKBytesResponse")
    public Long getDocImageMinSizeKBytes();

    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetDocImageMaxSizeKBytes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMaxSizeKBytes")
    @WebResult(name = "GetDocImageMaxSizeKBytesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocImageMaxSizeKBytes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMaxSizeKBytes")
    @ResponseWrapper(localName = "GetDocImageMaxSizeKBytesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMaxSizeKBytesResponse")
    public Long getDocImageMaxSizeKBytes();

    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetDocImageMinWidthResolution", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinWidthResolution")
    @WebResult(name = "GetDocImageMinWidthResolutionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocImageMinWidthResolution", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinWidthResolution")
    @ResponseWrapper(localName = "GetDocImageMinWidthResolutionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinWidthResolutionResponse")
    public Long getDocImageMinWidthResolution();

    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "GetDocImageMinHeightResolution", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinHeightResolution")
    @WebResult(name = "GetDocImageMinHeightResolutionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocImageMinHeightResolution", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinHeightResolution")
    @ResponseWrapper(localName = "GetDocImageMinHeightResolutionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageMinHeightResolutionResponse")
    public Long getDocImageMinHeightResolution();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfstring
     */
    @WebMethod(operationName = "GetDocImageSupportedFileTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageSupportedFileTypes")
    @WebResult(name = "GetDocImageSupportedFileTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocImageSupportedFileTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageSupportedFileTypes")
    @ResponseWrapper(localName = "GetDocImageSupportedFileTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocImageSupportedFileTypesResponse")
    public ArrayOfstring getDocImageSupportedFileTypes();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCountry
     */
    @WebMethod(operationName = "GetPassportCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPassportCountries")
    @WebResult(name = "GetPassportCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPassportCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPassportCountries")
    @ResponseWrapper(localName = "GetPassportCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPassportCountriesResponse")
    public ArrayOfGlobalCountry getPassportCountries();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCountry
     */
    @WebMethod(operationName = "GetIdentityCardIssuingCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardIssuingCountries")
    @WebResult(name = "GetIdentityCardIssuingCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetIdentityCardIssuingCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetIdentityCardIssuingCountries")
    @ResponseWrapper(localName = "GetIdentityCardIssuingCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetIdentityCardIssuingCountriesResponse")
    public ArrayOfGlobalCountry getIdentityCardIssuingCountries();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCountry
     */
    @WebMethod(operationName = "GetIdentityCardNationalityCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardNationalityCountries")
    @WebResult(name = "GetIdentityCardNationalityCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetIdentityCardNationalityCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetIdentityCardNationalityCountries")
    @ResponseWrapper(localName = "GetIdentityCardNationalityCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetIdentityCardNationalityCountriesResponse")
    public ArrayOfGlobalCountry getIdentityCardNationalityCountries();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCountry
     */
    @WebMethod(operationName = "GetLocationCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationCountries")
    @WebResult(name = "GetLocationCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetLocationCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLocationCountries")
    @ResponseWrapper(localName = "GetLocationCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLocationCountriesResponse")
    public ArrayOfGlobalCountry getLocationCountries();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalProvince
     */
    @WebMethod(operationName = "GetLocationStates", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationStates")
    @WebResult(name = "GetLocationStatesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetLocationStates", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLocationStates")
    @ResponseWrapper(localName = "GetLocationStatesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLocationStatesResponse")
    public ArrayOfGlobalProvince getLocationStates();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalProvince
     */
    @WebMethod(operationName = "GetItalyProvinceOfBirth", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItalyProvinceOfBirth")
    @WebResult(name = "GetItalyProvinceOfBirthResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetItalyProvinceOfBirth", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetItalyProvinceOfBirth")
    @ResponseWrapper(localName = "GetItalyProvinceOfBirthResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetItalyProvinceOfBirthResponse")
    public ArrayOfGlobalProvince getItalyProvinceOfBirth();

    /**
     * 
     * @param id
     * @return
     *     returns com.starlix.service.id3.GlobalItemCheckResultCodes
     */
    @WebMethod(operationName = "GetItemCheckResultCodes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItemCheckResultCodes")
    @WebResult(name = "GetItemCheckResultCodesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetItemCheckResultCodes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetItemCheckResultCodes")
    @ResponseWrapper(localName = "GetItemCheckResultCodesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetItemCheckResultCodesResponse")
    public GlobalItemCheckResultCodes getItemCheckResultCodes(
        @WebParam(name = "ID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long id);

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSanctionsIssuer
     */
    @WebMethod(operationName = "GetSanctionsIssuers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSanctionsIssuers")
    @WebResult(name = "GetSanctionsIssuersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSanctionsIssuers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSanctionsIssuers")
    @ResponseWrapper(localName = "GetSanctionsIssuersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSanctionsIssuersResponse")
    public ArrayOfGlobalSanctionsIssuer getSanctionsIssuers();

    /**
     * 
     * @param itemcheckID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSearchPurpose
     */
    @WebMethod(operationName = "GetSearchPurposes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSearchPurposes")
    @WebResult(name = "GetSearchPurposesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSearchPurposes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSearchPurposes")
    @ResponseWrapper(localName = "GetSearchPurposesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSearchPurposesResponse")
    public ArrayOfGlobalSearchPurpose getSearchPurposes(
        @WebParam(name = "itemcheckID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long itemcheckID);

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSanctionsIssuer
     */
    @WebMethod(operationName = "GetFCRASanctionsIssuers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetFCRASanctionsIssuers")
    @WebResult(name = "GetFCRASanctionsIssuersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetFCRASanctionsIssuers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetFCRASanctionsIssuers")
    @ResponseWrapper(localName = "GetFCRASanctionsIssuersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetFCRASanctionsIssuersResponse")
    public ArrayOfGlobalSanctionsIssuer getFCRASanctionsIssuers();

    /**
     * 
     * @param cardType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCardName", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCardName")
    @WebResult(name = "GetCardNameResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCardName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCardName")
    @ResponseWrapper(localName = "GetCardNameResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCardNameResponse")
    public String getCardName(
        @WebParam(name = "CardType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalCardType cardType);

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfstring
     */
    @WebMethod(operationName = "GetDocumentTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocumentTypes")
    @WebResult(name = "GetDocumentTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDocumentTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocumentTypes")
    @ResponseWrapper(localName = "GetDocumentTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDocumentTypesResponse")
    public ArrayOfstring getDocumentTypes();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfstring
     */
    @WebMethod(operationName = "GetExtractVersions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractVersions")
    @WebResult(name = "GetExtractVersionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetExtractVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetExtractVersions")
    @ResponseWrapper(localName = "GetExtractVersionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetExtractVersionsResponse")
    public ArrayOfstring getExtractVersions();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfstring
     */
    @WebMethod(operationName = "GetExtractFormats", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractFormats")
    @WebResult(name = "GetExtractFormatsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetExtractFormats", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetExtractFormats")
    @ResponseWrapper(localName = "GetExtractFormatsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetExtractFormatsResponse")
    public ArrayOfstring getExtractFormats();

    /**
     * 
     * @param supplierName
     */
    @WebMethod(operationName = "SupplierUpdate", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/SupplierUpdate")
    @RequestWrapper(localName = "SupplierUpdate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SupplierUpdate")
    @ResponseWrapper(localName = "SupplierUpdateResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.SupplierUpdateResponse")
    public void supplierUpdate(
        @WebParam(name = "SupplierName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String supplierName);

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalSouthAfricaSupplier
     */
    @WebMethod(operationName = "GetSouthAfricaCreditSuppliers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSouthAfricaCreditSuppliers")
    @WebResult(name = "GetSouthAfricaCreditSuppliersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSouthAfricaCreditSuppliers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSouthAfricaCreditSuppliers")
    @ResponseWrapper(localName = "GetSouthAfricaCreditSuppliersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSouthAfricaCreditSuppliersResponse")
    public ArrayOfGlobalSouthAfricaSupplier getSouthAfricaCreditSuppliers();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalDVLADrivingLicenceEndorsement
     */
    @WebMethod(operationName = "GetDVLADrivingLicenceEndorsements", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDVLADrivingLicenceEndorsements")
    @WebResult(name = "GetDVLADrivingLicenceEndorsementsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDVLADrivingLicenceEndorsements", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDVLADrivingLicenceEndorsements")
    @ResponseWrapper(localName = "GetDVLADrivingLicenceEndorsementsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDVLADrivingLicenceEndorsementsResponse")
    public ArrayOfGlobalDVLADrivingLicenceEndorsement getDVLADrivingLicenceEndorsements();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalPEPTier
     */
    @WebMethod(operationName = "GetPEPTiers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPEPTiers")
    @WebResult(name = "GetPEPTiersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPEPTiers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPEPTiers")
    @ResponseWrapper(localName = "GetPEPTiersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPEPTiersResponse")
    public ArrayOfGlobalPEPTier getPEPTiers();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCIFASProductCode
     */
    @WebMethod(operationName = "GetCIFASProductCode", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCIFASProductCode")
    @WebResult(name = "GetCIFASProductCodeResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCIFASProductCode", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCIFASProductCode")
    @ResponseWrapper(localName = "GetCIFASProductCodeResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCIFASProductCodeResponse")
    public ArrayOfGlobalCIFASProductCode getCIFASProductCode();

    /**
     * 
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalCreditHeaderAccountType
     */
    @WebMethod(operationName = "GetCreditHeaderAccountTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCreditHeaderAccountTypes")
    @WebResult(name = "GetCreditHeaderAccountTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetCreditHeaderAccountTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCreditHeaderAccountTypes")
    @ResponseWrapper(localName = "GetCreditHeaderAccountTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetCreditHeaderAccountTypesResponse")
    public ArrayOfGlobalCreditHeaderAccountType getCreditHeaderAccountTypes();

}
