
package com.starlix.service.id3;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IGlobalSearch", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGlobalSearch {


    /**
     * 
     * @param authenticationID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalAuthenticationDetails
     * @throws IGlobalSearchGetAuthenticationDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAuthenticationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationDetails")
    @WebResult(name = "GetAuthenticationDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAuthenticationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAuthenticationDetails")
    @ResponseWrapper(localName = "GetAuthenticationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAuthenticationDetailsResponse")
    public GlobalAuthenticationDetails getAuthenticationDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID)
        throws IGlobalSearchGetAuthenticationDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param authenticationID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalAuthenticationDetails
     * @throws IGlobalSearchGetLatestAuthenticationDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetLatestAuthenticationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetLatestAuthenticationDetails")
    @WebResult(name = "GetLatestAuthenticationDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetLatestAuthenticationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLatestAuthenticationDetails")
    @ResponseWrapper(localName = "GetLatestAuthenticationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetLatestAuthenticationDetailsResponse")
    public GlobalAuthenticationDetails getLatestAuthenticationDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID)
        throws IGlobalSearchGetLatestAuthenticationDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param descendingOrder
     * @param endDate
     * @param searchType
     * @param sortType
     * @param pageSize
     * @param page
     * @param searchValue
     * @param orgID
     * @param startDate
     * @return
     *     returns com.starlix.service.id3.GlobalAuthentications
     * @throws IGlobalSearchGetAuthenticationsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAuthentications", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthentications")
    @WebResult(name = "GetAuthenticationsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAuthentications", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAuthentications")
    @ResponseWrapper(localName = "GetAuthenticationsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAuthenticationsResponse")
    public GlobalAuthentications getAuthentications(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar endDate,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String searchValue,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "SortType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long sortType,
        @WebParam(name = "DescendingOrder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean descendingOrder)
        throws IGlobalSearchGetAuthenticationsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param enable
     * @param authenticationID
     * @param orgID
     * @throws IGlobalSearchUpdateAuthenticationHelpdeskAccessID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateAuthenticationHelpdeskAccess", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationHelpdeskAccess")
    @RequestWrapper(localName = "UpdateAuthenticationHelpdeskAccess", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAuthenticationHelpdeskAccess")
    @ResponseWrapper(localName = "UpdateAuthenticationHelpdeskAccessResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAuthenticationHelpdeskAccessResponse")
    public void updateAuthenticationHelpdeskAccess(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean enable)
        throws IGlobalSearchUpdateAuthenticationHelpdeskAccessID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param profileUID
     * @param actionType
     * @param addRemoveOGMRecordResult
     * @param inputData
     * @param currentAccountID
     * @param profileVersion
     * @param customerReference
     * @param authenticationID
     * @param sError
     * @param sourceName
     * @param orgID
     * @throws IGlobalSearchAddRemoveOGMRecordID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "AddRemoveOGMRecord", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/AddRemoveOGMRecord")
    @RequestWrapper(localName = "AddRemoveOGMRecord", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AddRemoveOGMRecord")
    @ResponseWrapper(localName = "AddRemoveOGMRecordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.AddRemoveOGMRecordResponse")
    public void addRemoveOGMRecord(
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "CurrentAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String currentAccountID,
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String customerReference,
        @WebParam(name = "ProfileUID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String profileUID,
        @WebParam(name = "ProfileVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long profileVersion,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalInputData inputData,
        @WebParam(name = "ActionType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String actionType,
        @WebParam(name = "sError", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", mode = WebParam.Mode.INOUT)
        Holder<String> sError,
        @WebParam(name = "SourceName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", mode = WebParam.Mode.INOUT)
        Holder<String> sourceName,
        @WebParam(name = "AddRemoveOGMRecordResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", mode = WebParam.Mode.OUT)
        Holder<Boolean> addRemoveOGMRecordResult)
        throws IGlobalSearchAddRemoveOGMRecordID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sanctionID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalSanctionsEnforcementData
     * @throws IGlobalSearchGetSanctionsEnforcementsDataID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSanctionsEnforcementsData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSanctionsEnforcementsData")
    @WebResult(name = "GetSanctionsEnforcementsDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSanctionsEnforcementsData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSanctionsEnforcementsData")
    @ResponseWrapper(localName = "GetSanctionsEnforcementsDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSanctionsEnforcementsDataResponse")
    public GlobalSanctionsEnforcementData getSanctionsEnforcementsData(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "SanctionID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String sanctionID)
        throws IGlobalSearchGetSanctionsEnforcementsDataID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param sanctionID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalPEPIntelligenceData
     * @throws IGlobalSearchGetPEPIntelligenceDataID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetPEPIntelligenceData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetPEPIntelligenceData")
    @WebResult(name = "GetPEPIntelligenceDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetPEPIntelligenceData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPEPIntelligenceData")
    @ResponseWrapper(localName = "GetPEPIntelligenceDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetPEPIntelligenceDataResponse")
    public GlobalPEPIntelligenceData getPEPIntelligenceData(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "SanctionID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String sanctionID)
        throws IGlobalSearchGetPEPIntelligenceDataID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param endDate
     * @param searchType
     * @param format
     * @param searchValue
     * @param version
     * @param orgID
     * @param startDate
     * @return
     *     returns byte[]
     * @throws IGlobalSearchGetDataExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtract")
    @WebResult(name = "GetDataExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtract")
    @ResponseWrapper(localName = "GetDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtractResponse")
    public byte[] getDataExtract(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar endDate,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String searchValue,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long format,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String version)
        throws IGlobalSearchGetDataExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param repeat
     * @param name
     * @param start
     * @param format
     * @param end
     * @param type
     * @param version
     * @param orgID
     * @throws IGlobalSearchCreateDataExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateDataExtract")
    @RequestWrapper(localName = "CreateDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateDataExtract")
    @ResponseWrapper(localName = "CreateDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateDataExtractResponse")
    public void createDataExtract(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "Type", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalDataExtractType type,
        @WebParam(name = "Start", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar start,
        @WebParam(name = "End", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        XMLGregorianCalendar end,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        GlobalDataExtractFormat format,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String version,
        @WebParam(name = "Repeat", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean repeat)
        throws IGlobalSearchCreateDataExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param search
     * @param pageSize
     * @param page
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.GlobalDataExtracts
     * @throws IGlobalSearchGetDataExtractsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDataExtracts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtracts")
    @WebResult(name = "GetDataExtractsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDataExtracts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtracts")
    @ResponseWrapper(localName = "GetDataExtractsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtractsResponse")
    public GlobalDataExtracts getDataExtracts(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalSearchGetDataExtractsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param dataExtractID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalDataExtractDownloadHistory
     * @throws IGlobalSearchGetDataExtractHistoryID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDataExtractHistory", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractHistory")
    @WebResult(name = "GetDataExtractHistoryResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDataExtractHistory", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtractHistory")
    @ResponseWrapper(localName = "GetDataExtractHistoryResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDataExtractHistoryResponse")
    public ArrayOfGlobalDataExtractDownloadHistory getDataExtractHistory(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String dataExtractID)
        throws IGlobalSearchGetDataExtractHistoryID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param dataExtractID
     * @param orgID
     * @throws IGlobalSearchCancelDataExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CancelDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelDataExtract")
    @RequestWrapper(localName = "CancelDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CancelDataExtract")
    @ResponseWrapper(localName = "CancelDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CancelDataExtractResponse")
    public void cancelDataExtract(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String dataExtractID)
        throws IGlobalSearchCancelDataExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param dataExtractID
     * @param orgID
     * @return
     *     returns byte[]
     * @throws IGlobalSearchDownloadDataExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadDataExtract")
    @WebResult(name = "DownloadDataExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "DownloadDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DownloadDataExtract")
    @ResponseWrapper(localName = "DownloadDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DownloadDataExtractResponse")
    public byte[] downloadDataExtract(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String dataExtractID)
        throws IGlobalSearchDownloadDataExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param reportFolder
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalReportDetails
     * @throws IGlobalSearchGetReportsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetReports", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReports")
    @WebResult(name = "GetReportsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetReports", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReports")
    @ResponseWrapper(localName = "GetReportsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportsResponse")
    public ArrayOfGlobalReportDetails getReports(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "ReportFolder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String reportFolder)
        throws IGlobalSearchGetReportsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param path
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalReportParameter
     * @throws IGlobalSearchGetReportParametersID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetReportParameters", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportParameters")
    @WebResult(name = "GetReportParametersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetReportParameters", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportParameters")
    @ResponseWrapper(localName = "GetReportParametersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportParametersResponse")
    public ArrayOfGlobalReportParameter getReportParameters(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Path", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String path)
        throws IGlobalSearchGetReportParametersID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param path
     * @param pageNumber
     * @param format
     * @param pageRoot
     * @param streamRoot
     * @param parameters
     * @param orgID
     * @return
     *     returns byte[]
     * @throws IGlobalSearchGetReportID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetReport", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReport")
    @WebResult(name = "GetReportResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetReport", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReport")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportResponse")
    public byte[] getReport(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "Path", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String path,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String format,
        @WebParam(name = "StreamRoot", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String streamRoot,
        @WebParam(name = "PageRoot", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String pageRoot,
        @WebParam(name = "Parameters", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        ArrayOfGlobalReportParameter parameters,
        @WebParam(name = "PageNumber", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Integer pageNumber)
        throws IGlobalSearchGetReportID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param imageID
     * @param requestID
     * @param orgID
     * @return
     *     returns byte[]
     * @throws IGlobalSearchGetReportImageID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetReportImage", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportImage")
    @WebResult(name = "GetReportImageResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetReportImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportImage")
    @ResponseWrapper(localName = "GetReportImageResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetReportImageResponse")
    public byte[] getReportImage(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "RequestID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String requestID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String imageID)
        throws IGlobalSearchGetReportImageID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param authenticationID
     * @param entityID
     * @param orgID
     * @return
     *     returns java.lang.String
     * @throws IGlobalSearchGetDetailedInvestigationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDetailedInvestigation", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigation")
    @WebResult(name = "GetDetailedInvestigationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDetailedInvestigation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDetailedInvestigation")
    @ResponseWrapper(localName = "GetDetailedInvestigationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDetailedInvestigationResponse")
    public String getDetailedInvestigation(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "Entity_ID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String entityID)
        throws IGlobalSearchGetDetailedInvestigationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param searchID
     * @param caseID
     * @param fcraEnabled
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalFCRAMatchDetails
     * @throws IGlobalSearchGetFCRAMatchDetailsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetFCRAMatchDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetFCRAMatchDetails")
    @WebResult(name = "GetFCRAMatchDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetFCRAMatchDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetFCRAMatchDetails")
    @ResponseWrapper(localName = "GetFCRAMatchDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetFCRAMatchDetailsResponse")
    public ArrayOfGlobalFCRAMatchDetails getFCRAMatchDetails(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String caseID,
        @WebParam(name = "SearchID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String searchID,
        @WebParam(name = "FCRAEnabled", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean fcraEnabled)
        throws IGlobalSearchGetFCRAMatchDetailsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param authenticationID
     * @param orgID
     * @return
     *     returns com.starlix.service.id3.ArrayOfGlobalStatus
     * @throws IGlobalSearchGetSupplierExtendedStatusInformationID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetSupplierExtendedStatusInformation", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSupplierExtendedStatusInformation")
    @WebResult(name = "GetSupplierExtendedStatusInformationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetSupplierExtendedStatusInformation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierExtendedStatusInformation")
    @ResponseWrapper(localName = "GetSupplierExtendedStatusInformationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetSupplierExtendedStatusInformationResponse")
    public ArrayOfGlobalStatus getSupplierExtendedStatusInformation(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID)
        throws IGlobalSearchGetSupplierExtendedStatusInformationID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param enable
     * @param authenticationID
     * @param orgID
     * @throws IGlobalSearchUpdateAuthenticationDataDeletionID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateAuthenticationDataDeletion", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationDataDeletion")
    @RequestWrapper(localName = "UpdateAuthenticationDataDeletion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAuthenticationDataDeletion")
    @ResponseWrapper(localName = "UpdateAuthenticationDataDeletionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateAuthenticationDataDeletionResponse")
    public void updateAuthenticationDataDeletion(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean enable)
        throws IGlobalSearchUpdateAuthenticationDataDeletionID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param imageID
     * @param enable
     * @param orgID
     * @throws IGlobalSearchUpdateDIVDataDeletionID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateDIVDataDeletion", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateDIVDataDeletion")
    @RequestWrapper(localName = "UpdateDIVDataDeletion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateDIVDataDeletion")
    @ResponseWrapper(localName = "UpdateDIVDataDeletionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.UpdateDIVDataDeletionResponse")
    public void updateDIVDataDeletion(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String imageID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Boolean enable)
        throws IGlobalSearchUpdateDIVDataDeletionID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param accountType
     * @param name
     * @param format
     * @param orgId
     * @throws IGlobalSearchCreateUserAccountExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CreateUserAccountExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateUserAccountExtract")
    @RequestWrapper(localName = "CreateUserAccountExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateUserAccountExtract")
    @ResponseWrapper(localName = "CreateUserAccountExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CreateUserAccountExtractResponse")
    public void createUserAccountExtract(
        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgId,
        @WebParam(name = "name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String name,
        @WebParam(name = "accountType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        EnumsUserAccountType accountType,
        @WebParam(name = "format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        EnumsFormat format)
        throws IGlobalSearchCreateUserAccountExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param filter
     * @param pageSize
     * @param page
     * @param orgId
     * @return
     *     returns com.starlix.service.id3.ExtractDetails
     * @throws IGlobalSearchGetAccountExtractsID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountExtracts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAccountExtracts")
    @WebResult(name = "GetAccountExtractsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetAccountExtracts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountExtracts")
    @ResponseWrapper(localName = "GetAccountExtractsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetAccountExtractsResponse")
    public ExtractDetails getAccountExtracts(
        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgId,
        @WebParam(name = "page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long page,
        @WebParam(name = "pageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long pageSize,
        @WebParam(name = "filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        Long filter)
        throws IGlobalSearchGetAccountExtractsID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param extractId
     * @param orgId
     * @throws IGlobalSearchCancelExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CancelExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelExtract")
    @RequestWrapper(localName = "CancelExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CancelExtract")
    @ResponseWrapper(localName = "CancelExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.CancelExtractResponse")
    public void cancelExtract(
        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String extractId)
        throws IGlobalSearchCancelExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param extractId
     * @param orgId
     * @return
     *     returns byte[]
     * @throws IGlobalSearchDownloadExtractID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "DownloadExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadExtract")
    @WebResult(name = "DownloadExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "DownloadExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DownloadExtract")
    @ResponseWrapper(localName = "DownloadExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.DownloadExtractResponse")
    public byte[] downloadExtract(
        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String extractId)
        throws IGlobalSearchDownloadExtractID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param extractId
     * @param orgId
     * @return
     *     returns com.starlix.service.id3.ArrayOfHistoryAccountHistory
     * @throws IGlobalSearchGetUserAccountExtractHistoryID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetUserAccountExtractHistory", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetUserAccountExtractHistory")
    @WebResult(name = "GetUserAccountExtractHistoryResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetUserAccountExtractHistory", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetUserAccountExtractHistory")
    @ResponseWrapper(localName = "GetUserAccountExtractHistoryResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetUserAccountExtractHistoryResponse")
    public ArrayOfHistoryAccountHistory getUserAccountExtractHistory(
        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String extractId)
        throws IGlobalSearchGetUserAccountExtractHistoryID3GExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param authenticationID
     * @param entityID
     * @param orgID
     * @return
     *     returns byte[]
     * @throws IGlobalSearchGetDetailedInvestigationPDFID3GExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDetailedInvestigationPDF", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigationPDF")
    @WebResult(name = "GetDetailedInvestigationPDFResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    @RequestWrapper(localName = "GetDetailedInvestigationPDF", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDetailedInvestigationPDF")
    @ResponseWrapper(localName = "GetDetailedInvestigationPDFResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.starlix.service.id3.GetDetailedInvestigationPDFResponse")
    public byte[] getDetailedInvestigationPDF(
        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String authenticationID,
        @WebParam(name = "Entity_ID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        String entityID)
        throws IGlobalSearchGetDetailedInvestigationPDFID3GExceptionFaultFaultMessage
    ;

}
